#!/bin/bash

system_type=$(uname -s)

# MacOS specific configuration
if [ "$system_type" = "Darwin" ]; then
  echo "Configuring MacOS"

  # Update xcode
  softwareupdate --all --install --force

  # Install homebrew
  echo "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Install packages
  macos_packages=(
      # Casks
      'firefox-developer-edition'
      'google-chrome'
      'steam'
      'spotify'
      'streamlabs-obs'
      'ubersicht'
      'visual-studio-code'
      'vlc'
      'postman'
      'godot'
      'font-hack'
      'blender'
      'alacritty'
      'discord-canary'

      # Formulae
      'bat'
      'unp'
      'diff-so-fancy'
      'cowsay'
      'eslint'
      'chafa'
      'ca-certificates'
      'exa'
      'exiftool'
      'fd'
      'figlet'
      'fish'
      'fisher'
      'fzf'
      'ghostscript'
      'gcc'
      'go'
      'gotop'
      'gtop'
      'gzip'
      'htop'
      'imagemagick'
      'ipython'
      'lolcat'
      'lsusb'
      'ncurses'
      'neofetch'
      'neovim'
      'nmap'
      'node'
      'openssl@1.1'
      'openssl@3'
      'pandoc'
      'p7zip'
      'zsh'
      'yarn'
      'yadm'
      'wget'
      'tmux'
      'sqlite'
      'skhd'
      'ripgrep'
      'qemu'
      'python@3.10'
      'prettyping'
      'yabai'
      'android-platform-tools'
      'spotifyd'
      'oha'
  )

  # Set homebrew SSH key so we don't get rate limited
  # Tap into the brew repositories we need
  brew_taps=(
      'khanhas/tap'
      'koekeishiya/formulae'
      'railwaycat/emacsmacport'
      'sidneys/homebrew'
      'cmacrae/formulae'
      'homebrew/cask-versions'
      'homebrew/cask-fonts'
  )

  for tap in "${brew_taps[@]}"; do
    /opt/homebrew/bin/brew tap $tap
  done

  # Install the packages
  for package in "${macos_packages[@]}"; do
    /opt/homebrew/bin/brew install $package
  done

  # Install emacs prereqs
  /opt/homebrew/bin/brew install git ripgrep coreutils fd
  # Install clang
  xcode-select --install
  # Install emacs because it needs special flags
  /opt/homebrew/bin/brew install railwaycat/emacsmacport/emacs-mac --with-no-title-bars --with-emacs-sexy-icon --with-mac-metal --with-modules --with-imagemagick
  # Copy that Emacs.app to /Applications/Emacs.app
  rm -rf /Applications/Emacs.app
  cp -R /opt/homebrew/Cellar/emacs-mac/**/Emacs.app /Applications/

  # Setup Yabai if SIP is disabled
  if [ "$(csrutil status)" == "System Integrity Protection status: enabled." ]; then
      echo "SIP currently enabled. To install Yabai, disable SIP https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection"
  else
      echo "Installing Yabai"
      /opt/homebrew/bin/brew install koekeishiya/formulae/yabai
      sudo /opt/homebrew/bin/yabai --load-sa
      brew services start yabai

      # TODO - Modify /etc/sudoers to allow scripting additions to run on startup
      # https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
  fi
  # Decrypt stuff
  /opt/homebrew/bin/yadm decrypt

  # Change YADM remote to ssh
  /opt/homebrew/bin/yadm remote set-url origin git@github.com:wrathofrathma/dotfiles.git
fi



# Debian-based specific

# Arch linux specific


# Setup simple-bar

# Setup NVM

# Install Doom Emacs
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install

# Neovim / vim configuration

# Bootstrap Fish shell

# Bootstrap zsh
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

# Bootstrap tmux
