#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II III IV V 
bspc monitor DP-2 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Theming
# Lavender focused window
bspc config focused_border_color "#b4befe" 
# Greyish normal borders
bspc config normal_border_color "#6c7086"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam instance=Alien desktop='^2'

~/.screenlayout/default.sh
polybar main &
polybar secondary &
picom &
feh --bg-center ~/.wallpapers/yourname.jpg
